<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        <?php echo $this->model->site_title; ?>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ACARSD server website" />
    <meta name="keywords" content="acars, acarsd, airplanes, airplane communication, aviation, plane spotting" />
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
    <!-- Animate.css -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="css/bootstrap.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/magnific-popup.css">
    <!-- Main style  -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>

<body>
    <div class="loader"></div>
    <div id="page">
        <nav class="nav" role="navigation">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div id="logo"><a href="index.html">ACARSD <span>SERVER</span></a></div>
                    </div>
                </div>
            </div>
        </nav>
        <header id="header" class="cover" role="banner" style="background-image:url(images/airplane-cockpit.jpg);">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-md-offset-0 text-center">
                        <div class="display-t">
                            <div class="display-tc animate-box" data-animate-effect="fadeInUp">
                                <h1 class="mb30">Location: <?php echo $this->model->location; ?><br />Frequency: <?php echo $this->model->frequency; ?></h1>
                                <p> <a href="#" class="btn btn-primary" id="view">View Live Feed Now</a> </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div id="live-feed" class="bg-section">
            <div class="container">
                <div class="row row-pb-md">
                    <div class="col-md-8 col-md-offset-2 text-center animate-box" data-animate-effect="fadeInUp">
                        <div class="heading">
                            <h2>Live ACARS Feed</h2>
                            <p>Below is the live feed for this ACARSD server.</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-sm-4">
                        <div class="feature-center animate-box" data-animate-effect="fadeInUp" style="text-align:center;"> <pre id="messages">
                            </pre>
                            <br /> <a href="#" title="Live Postion Map" id="view_map">View Position Map</a> </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="feature-center animate-box" data-animate-effect="fadeInUp">
                            <div id="airplane-photos"> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row copyright">
            <div class="col-md-12 text-center">
                <p> <small class="block">All content is &copy; of their respective owners. Images from Airliners.net are &copy; and all rights reserved to the respective photographer.</small></p>
            </div>
        </div>
    </div>
    </footer>
    </div>
    <div class="gototop js-top"> <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a> </div>
    <!-- jQuery -->
    <script src="js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="js/jquery.waypoints.min.js"></script>
    <!-- Main -->
    <script src="js/main.js"></script>
</body>

</html>